### ISSUE TITLE
第一个star，哈哈

### ISSUE THREAD

**Issue by huayuanp** [Jrohy/v2ray.fun#1]
提几个建议 ，
希望脚本能自动更改系统的时间;
另外http/2不会弄啊,能不能加个wiki什么的。
谢谢作者。

**Comment by Jrohy** [comment]
确实少了同步时间的操作，会补上
http/2在更改配置里面子菜单有，后期可能会加些wiki教程
谢谢支持蛤

**Comment by Jrohy** [comment]
时间同步已加入， http/2设置菜单可以看下最新的截图
