### ISSUE TITLE
LEDE 上的客户端必须要有 "outbound" 。

### ISSUE THREAD

**Issue by allenchennnn** [Jrohy/v2ray.fun#10]
生成的配置文件中没有 outbound 。导致在 LEDE 上用不了。

**Comment by Jrohy** [comment]
有的这个是客户端配置文件必备的，请检查下

**Comment by allenchennnn** [comment]
不好意思，找到了。但是:
【2018年06月30日 07:56:38】: V2Ray配置文件没有通过测试，请检查设置!!!
