### ISSUE TITLE
socks 5 使用udp流量时爆内存

### ISSUE THREAD

**Issue by Seekerzero** [Jrohy/v2ray.fun#11]
socks 5 使用udp流量时爆内存
日志文件过载。

**Comment by Jrohy** [comment]
请出示报错日志

**Comment by Seekerzero** [comment]
2018/07/09 00:08:31 [Info] [2326064960] Transport|Internet|UDP: failed to handle UDP input > io: read/write on closed pipe
2018/07/09 00:08:31 [Info] Transport|Internet|UDP: establishing new connection for udp:18.219.25.71:13132
另外，再开启socks5 udp的时候cpu的压力也很大

**Comment by Jrohy** [comment]
这个，可以向v2ray官方反应，脚本只做方便修改json改变传输方式
